version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vehicle-sales-manager-v2-postgres
    environment:
      POSTGRES_USER: shido
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: vehicle-sales-manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shido"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
