# Perfil local â€” banco Docker em localhost:5432
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle-sales-manager
    username: ${DB_USER:shido}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
